#!/usr/bin/env bash

# The contents of the log file are given in stdin.
cat /dev/stdin | awk '
function alen( a, i) {
    for( i in a);
    return i
}

# Fields are separated via \t
BEGIN { FS = "\t" }

# count transactions
BEGIN { transactions = 0 }

# set variable for storing tid
BEGIN { last_tid = "" }


# count tids
{
  if( $2 != last_tid ) {
    ++transactions;
    last_tid=$2
  }
}
# record transaction ips
{
  if( $3 == "ssh" || $3 == "http") {
    ips[$6]++
  }
}

# print results
END {
  printf("     transactions     \n======================\n")
  for(ip in ips) {
    printf(" %-5s%s\n", ips[ip], substr(ip, 6))
  }
  printf("----------------------\n %-5d%s\n", transactions, "total")
}
'
